name: PostService

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 9 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install node modules
        run: npm install

      - name: run the node script
        run: |
          RES_TITLE=$(LAST_POST="${{ secrets.LAST_POST }}" SLACK_TOKEN=${{ secrets.SLACK_TOKEN }} SLACK_CHANNELS=${{ secrets.SLACK_CHANNELS }} node index.js)
          echo "POST_TITLE=$RES_TITLE" >> $GITHUB_ENV

      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'LAST_POST'
          value: ${{ env.POST_TITLE }}
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
